# Site settings
title: Code Abode
header-img: img/home-bg.png
email: jordan.kline@gmail.com
copyright_name: jordaninthewind
description: > # this means to ignore newlines until "baseurl:"
  Home is Where the Code Is
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jordaninthewind
learn_profile: jordaninthewind
email_username: jordan.kline@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
